// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/zorish-feed/ConversationWeb.tsx": () => import("../components/mockups/zorish-feed/ConversationWeb.tsx"),
  "./components/mockups/zorish-feed/Editorial.tsx": () => import("../components/mockups/zorish-feed/Editorial.tsx"),
  "./components/mockups/zorish-feed/ProximityZones.tsx": () => import("../components/mockups/zorish-feed/ProximityZones.tsx")
};
